#!/bin/bash

#create new bedrock project in sites
cd ~/sites/
git clone git@github.com:danv-stealthmedia/$1.git $1
cd ~/sites/$1


#create update env file
touch .env
echo "DB_NAME=$1" | sudo tee -a .env
echo "DB_USER=dan" | sudo tee -a .env
echo "DB_PASSWORD=dan" | sudo tee -a .env
echo "DB_HOST=localhost" | sudo tee -a .env
echo "DB_PREFIX=wp_" | sudo tee -a .env
echo "WP_ENV=development" | sudo tee -a .env
echo "WP_HOME=http://$1.test" | sudo tee -a .env
echo "WP_SITEURL=${WP_HOME}/wp" | sudo tee -a .env
echo "WP_DEBUG_LOG=/path/to/debug.log" | sudo tee -a .env
echo "AUTH_KEY=&sy&jkot]%Q[Ho=S7g9,0[pAg:VU,k{>@O@,iqm8+7eXk6[DwS]a.2mI>)mD+he*" | sudo tee -a .env
echo "SECURE_AUTH_KEY=z{t]r8Y1FEv#dUDp0PrW3V]Ud&(=K.',Lc/')bd*lMAR!A!DviEY/VtqB?I(_R['" | sudo tee -a .env
echo "LOGGED_IN_KEY=1JlXlM^:m/aw*LSocEK@=zjGplo0W1-2dLmBSTrHiQEa0E0GG/)Ab]mo#-0UP)0." | sudo tee -a .env
echo "NONCE_KEY=CY6s*vf!|sNwL0fBBne1BW*H3_27fQ(|0GQ!'{aaMUU0y!M(9'UM>0K|F:gh,4^q" | sudo tee -a .env
echo "AUTH_SALT=<ai/SQ8V4/.[p7wD|dy![BF(O&?st-5r1BlovzYRMr_)}S*%UD,<IvIcBg:sD5Fa" | sudo tee -a .env
echo "SECURE_AUTH_SALT=^(@Y!|{/lumQQG}ldWT?;'A3;]P5q*v<r+skW!S0=UN&w+z*j>C:^KS)c&-oPpDW" | sudo tee -a .env
echo "LOGGED_IN_SALT=2FTg7oT2zh+}gK,YrJ72h.K+om17-](IPXb}8i6C[Wqpz?t}Lgapl-UkyU]+iAPK" | sudo tee -a .env
echo "NONCE_SALT=[KZd<%Bv_FQ}w$q0Y*:;0bWnVh}tti(RQ!e1b9flDvX8YfceP<C4't%!-(BeXTdw" | sudo tee -a .env

#run composer
composer install

bundle install

#go to themes
cd ~/sites/$1/web/app/themes/$1
yarn
yarn build


#add htaccess
cd ~/sites/$1/web
touch .htaccess
echo "# BEGIN WordPress" | sudo tee -a .htaccess
echo "RewriteEngine On" | sudo tee -a .htaccess
echo "RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]" | sudo tee -a .htaccess
echo "RewriteBase /" | sudo tee -a .htaccess
echo "RewriteRule ^index\.php$ - [L]" | sudo tee -a .htaccess
echo "RewriteCond %{REQUEST_FILENAME} !-f" | sudo tee -a .htaccess
echo "RewriteCond %{REQUEST_FILENAME} !-d" | sudo tee -a .htaccess
echo "RewriteRule . /index.php [L]" | sudo tee -a .htaccess
echo "# END WordPress" | sudo tee -a .htaccess

#edit hosts file
cd /mnt/c/Windows/System32/drivers/etc/
echo 127.0.0.1 $1.test>>hosts

#create vhosts and enable
cd /etc/apache2/sites-available
sudo touch $1.conf

echo "<VirtualHost *:80>" | sudo tee -a $1.conf
echo "ServerAdmin dan@localhost" | sudo tee -a $1.conf
echo "ServerName $1.test" | sudo tee -a $1.conf
echo "DocumentRoot /home/dan/sites/$1/web" | sudo tee -a $1.conf
echo "<Directory /home/dan/sites/$1/web>" | sudo tee -a $1.conf
echo "Options Indexes FollowSymlinks Multiviews" | sudo tee -a $1.conf
echo "AllowOverride All" | sudo tee -a $1.conf
echo "Require all granted" | sudo tee -a $1.conf
echo "</Directory>" | sudo tee -a $1.conf
echo "ErrorLog ${APACHE_LOG_DIR}/error.log" | sudo tee -a $1.conf
echo "CustomLog ${APACHE_LOG_DIR}/access.log combined" | sudo tee -a $1.conf
echo "</VirtualHost>" | sudo tee -a $1.conf
sudo a2ensite $1.conf

#restart apache
sudo service apache2 restart

#create db
mysql -u dan -p